  kind: pipeline
  type: docker
  name: default
  steps:
    - name: build
      image: hub.codefirst.iut.uca.fr/camille.petitalot/drone-sonarplugin-reactnative:latest
      commands:
        - cd JokesApp
        - npm install