  kind: pipeline
  type: docker
  name: default
  steps:
    - name: build
      image: hub.codefirst.iut.uca.fr/camille.petitalot/drone-sonarplugin-reactnative:latest
      commands:
        - cd JokesApp
        - npm install
        
    - name : sonar 
      image :  hub.codefirst.iut.uca.fr/camille.petitalot/drone-sonarplugin-reactnative:latest
      environment:
        sonar_host: https://codefirst.iut.uca.fr/sonar/
        sonar_token:
          from_secret: SECRET_SONAR_LOGIN
        project_key: JokesAppSonar
      commands:
        - cd JokesApp
        - npm install
        - sonar-scanner -Dsonar.projectKey=$${project_key} -Dsonar.sources=. -Dsonar.host.url=$${sonar_host} -Dsonar.login=$${sonar_token}